import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

type Leaf = { $value: string | number };
type Group = { [key: string]: Leaf | Group | number[] };
export type Tokens = Record<string, Group>;

const isLeaf = (node: unknown): node is Leaf =>
  typeof node === "object" && node !== null && "$value" in node;

function flatten(group: Group, path: string[] = []): [string, string | number][] {
  return Object.entries(group).flatMap(([key, node]) => {
    if (Array.isArray(node)) return [];
    if (isLeaf(node)) return [[[...path, key].join("-"), node.$value] as [string, string | number]];
    return flatten(node, [...path, key]);
  });
}

const decls = (entries: [string, string | number][], indent = "  ") =>
  entries.map(([name, value]) => `${indent}--${name}: ${value};`).join("\n");

/** Theme-dependent tokens live under `<group>.light` / `<group>.dark`. */
function themed(tokens: Tokens, theme: "light" | "dark"): [string, string | number][] {
  return Object.entries(tokens).flatMap(([name, group]) =>
    group[theme] && !isLeaf(group[theme]) ? flatten(group[theme] as Group, [name]) : [],
  );
}

function shared(tokens: Tokens): [string, string | number][] {
  const out: [string, string | number][] = [];
  for (const [name, group] of Object.entries(tokens)) {
    if (group.light || group.dark) continue;
    out.push(...flatten(group, [name]));
  }
  return out;
}

export function buildCss(tokens: Tokens): string {
  const base = shared(tokens).filter(([n]) => !n.startsWith("font-size-"));
  const space = tokens.space?.steps as unknown as number[];
  const spaceVars: [string, string][] = space.map((n) => [`space-${n}`, `calc(var(--space-unit) * ${n})`]);
  const sizes = flatten(tokens.font?.size as Group, ["font", "size"]).map(
    ([n, v]) => [n, `calc(${v}rem * var(--font-scale))`] as [string, string],
  );
  const light = themed(tokens, "light");
  const dark = themed(tokens, "dark");

  return [
    "/* generated by packages/tokens/src/build.ts — do not edit */",
    "@layer tokens {",
    `:root {\n${decls([...base, ...spaceVars, ...sizes])}\n${decls(light)}\n  color-scheme: light;\n}`,
    `@media (prefers-color-scheme: dark) {\n  :root:not([data-theme="light"]) {\n${decls(dark, "    ")}\n    color-scheme: dark;\n  }\n}`,
    `:root[data-theme="dark"] {\n${decls(dark)}\n  color-scheme: dark;\n}`,
    "}",
    "",
  ].join("\n");
}

export type Surfaces = { surface: Record<string, Record<string, string | number>> };

/** Surface profiles only override variables, so components never branch on surface. */
export function buildSurfacesCss(surfaces: Surfaces): string {
  const blocks = Object.entries(surfaces.surface).map(
    ([name, vars]) =>
      // html:root beats the dark-mode `:root:not([data-theme])` block regardless of load order
      `html:root[data-surface="${name}"] {\n${decls(Object.entries(vars))}\n}`,
  );
  return [
    "/* generated by packages/tokens/src/build.ts — do not edit */",
    "@layer tokens {",
    ...blocks,
    "}",
    "",
  ].join("\n");
}

const here = dirname(fileURLToPath(import.meta.url));
if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  const tokens = JSON.parse(readFileSync(resolve(here, "tokens.json"), "utf8")) as Tokens;
  const surfaces = JSON.parse(readFileSync(resolve(here, "surfaces.json"), "utf8")) as Surfaces;
  const dist = resolve(here, "../dist");
  mkdirSync(dist, { recursive: true });
  writeFileSync(resolve(dist, "tokens.css"), buildCss(tokens));
  writeFileSync(resolve(dist, "surfaces.css"), buildSurfacesCss(surfaces));
  console.log(`wrote ${dist}/tokens.css, surfaces.css`);
}
